on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        #find_vulnerabilities: true
        #sarif_upload: true
        #iac_dir:
        #policy_path:
        #skip_rules:
        #config_path:
        #scm_token:
        #webhook_url:
        #webhook_token:
